<?php

namespace AppBundle\Repository;

/**
 * MessagePriveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagePriveRepository extends \Doctrine\ORM\EntityRepository
{
}
