<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll($first_result = 1, $max_results = 12)
    {
        $qb = $this->createQueryBuilder('thread');
        $qb ->select('thread')
            ->setFirstResult(($first_result-1)*$max_results)
            ->setMaxResults($max_results);

        return new Paginator($qb);
    }
}
